language: node_js
node_js:
  - 'stable'
env:
  global:
    - CC_TEST_REPORTER_ID = 51cdafb0a6a93164ea9cacaac31248efa470bf9fb0acb44259725086feee1d14
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn run test:cov
  - yarn run lint
after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
